// Generated by gencpp from file pathsplit/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PATHSPLIT_MESSAGE_ADDTWOINTS_H
#define PATHSPLIT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <pathsplit/AddTwoIntsRequest.h>
#include <pathsplit/AddTwoIntsResponse.h>


namespace pathsplit
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace pathsplit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pathsplit::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::pathsplit::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::pathsplit::AddTwoInts > {
  static const char* value()
  {
    return "pathsplit/AddTwoInts";
  }

  static const char* value(const ::pathsplit::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::pathsplit::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::pathsplit::AddTwoInts > 
template<>
struct MD5Sum< ::pathsplit::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pathsplit::AddTwoInts >::value();
  }
  static const char* value(const ::pathsplit::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pathsplit::AddTwoIntsRequest> should match 
// service_traits::DataType< ::pathsplit::AddTwoInts > 
template<>
struct DataType< ::pathsplit::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::pathsplit::AddTwoInts >::value();
  }
  static const char* value(const ::pathsplit::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pathsplit::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::pathsplit::AddTwoInts > 
template<>
struct MD5Sum< ::pathsplit::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pathsplit::AddTwoInts >::value();
  }
  static const char* value(const ::pathsplit::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pathsplit::AddTwoIntsResponse> should match 
// service_traits::DataType< ::pathsplit::AddTwoInts > 
template<>
struct DataType< ::pathsplit::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::pathsplit::AddTwoInts >::value();
  }
  static const char* value(const ::pathsplit::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATHSPLIT_MESSAGE_ADDTWOINTS_H
