function dim = CasadiPolygonSize(SXdim)
    dim = if_else(SXdim == 1, 1, ...
          if_else(SXdim == 2, 2, ...
          if_else(SXdim == 3, 3, ...
          if_else(SXdim == 4, 4, ...
          if_else(SXdim == 5, 5, 6)))));
end